### ISSUE TITLE
integrate vibration while silent

### ISSUE THREAD

**Issue by soumyakantpadhee** [nikashitsa/polar-h10-alert#2]
Can you please add  a vibration or sound option.

**Comment by nikashitsa** [comment]
Sound is already there. Did you mean the option to select between sound and vibration? Could you please clarify?

**Comment by soumyakantpadhee** [comment]
Yes. At times the sound seems very loud. Can you create an option for sound or vibration.

**Comment by nikashitsa** [comment]
Ok, I got your idea. Will work on it, thanks!

**Comment by nikashitsa** [comment]
Looks like I can't add Vibration option, but I've added sound option https://github.com/nikashitsa/polar-h10-alert/commit/f5594e2e6cf6f152a5564ed4afa2a221aae4ab01 
Now you can reduce sound as you wish 😊
