### ISSUE TITLE
How to get Strap ID?

### ISSUE THREAD

**Issue by avi0707** [nikashitsa/polar-h10-alert#5]
Im using a program hyperate on windows 10 also using Stream Deck to view heart rate at all times. But how to add to stream deck or how to get ID to send to stream deck? Thank you.

**Comment by nikashitsa** [comment]
I'm not completely understand your question. What is Stream Deck, what ID do you need? Could you please clarify?  
This is web app for Polar H10 devices.

**Comment by avi0707** [comment]
No it’s ok your program works fantastic.  Thank you.Sent from my iPhoneOn 31 Jul 2023, at 3:26 AM, Nikita Verkhovin ***@***.***> wrote:﻿
I'm not completely understand your question. What is Stream Deck, what ID do you need? Could you please clarify?
This is web app for Polar H10 devices.

**Comment by avi0707** [comment]
Anyway to stop the screen in blue fly and iOS from minimise or go to iPhone home scree. I disabled screen turn off in settings but it still does it. I have to refresh page again and connect to get audio working.   Nothing else is running. Is there a way to select numbers up and down with better accuracy like a bigger button or slider or maybe an increment selector. Thanks Arnold Sent from my iPhoneOn 31 Jul 2023, at 5:12 AM, Avi0707 ***@***.***> wrote:﻿No it’s ok your program works fantastic.  Thank you.Sent from my iPhoneOn 31 Jul 2023, at 3:26 AM, Nikita Verkhovin ***@***.***> wrote:﻿
I'm not completely understand your question. What is Stream Deck, what ID do you need? Could you please clarify?
This is web app for Polar H10 devices.
